(ns riceops.render-html
  "Build-time HTML renderer for `docs/samples/operator-console.html`.

  Closes flagship checklist item 2 (ADR-2607189300 at
  `com-junkawasaki/root`): a GitHub Pages operator console generated by
  actually RUNNING the real actor stack at build time, never a
  hand-typed mockup.

  This namespace drives a genuine multi-disposition scenario through
  the compiled `riceops.operation/build` `langgraph-clj` StateGraph
  (advisor -> governor -> phase gate -> commit | request-approval ->
  commit | hold, the SAME `riceops.store/MemStore` seed data any
  operator would register), covering: auto-commits, an always-escalate
  op ACTUALLY resolved by resuming the interrupted graph
  (`interrupt-before #{:request-approval}` + checkpoint-based resume,
  same as `riceops.sim`), a high-cost escalate left pending
  (interrupted, never resumed), and four DISTINCT real HARD-hold
  reasons -- all real ids/ops native to THIS repo (`riceops.governor`'s
  own field-id/allowlist/blocked-op/water-level/acreage rules), never
  copied from another cloud-itonami vertical.

  Every disposition (:commit/:escalate/:hold) and every violation
  reason come from a REAL `langgraph.graph/run*` call against the real
  compiled StateGraph -- including the escalation resolution below,
  which is a genuine checkpoint resume (`:resume? true`), not a
  fabricated record. The only renderer-authored text is the human
  reviewer's free-text `:note` (e.g. what the agronomist actually said)
  -- the approval decision itself, `:by`, and the resulting `:commit`
  disposition all come straight out of the resumed graph state.

  Output is fully deterministic: no timestamps, no randomness, no
  external I/O in the rendered content -- reruns against this same
  fixed scenario produce byte-identical HTML (verified by diffing two
  consecutive runs), so nightly regeneration only ever commits when
  the actor's real behavior actually changes.

  Usage: `clojure -M:dev:render-html [out-file]`
  (default `docs/samples/operator-console.html`)."
  (:require [clojure.string :as str]
            [langgraph.graph :as g]
            [riceops.facts :as facts]
            [riceops.governor :as governor]
            [riceops.operation :as op]
            [riceops.store :as store]))

;; ----------------------------- scenario -----------------------------

(def ^:private operator-context
  {:actor-id "op-1" :role :farm-operator :phase :phase-3})

(defn- seed-store
  "Register the paddy fields this demo's requests reference. Real
  `riceops.store/MemStore`, not a stand-in."
  []
  (store/mem-store
   {:initial-fields
    {"paddy-001" {:id "paddy-001" :name "Green Delta North Paddy" :variety "japonica"}
     "paddy-002" {:id "paddy-002" :name "Green Delta South Paddy" :variety "indica"}
     "paddy-003" {:id "paddy-003" :name "Sunrise Terrace Paddy 3" :variety "glutinous"}}}))

(defn- run-op! [actor label request]
  {:label label
   :request request
   :result (:state (g/run* actor {:request request :context operator-context}
                          {:thread-id label}))})

(defn run-demo!
  "Drives 8 requests through the REAL compiled StateGraph
  (`riceops.operation/build` over a freshly seeded
  `riceops.store/MemStore`): 2 clean requests that auto-commit, 1
  always-escalate crop-health concern (resolved below via a genuine
  checkpoint resume), 1 high-cost supply order left pending
  (interrupted, never resumed), and 4 requests that each independently
  trip a DIFFERENT real Governor HARD-hold rule. Returns the ordered
  vector of `{:label :request :result}` runs -- every `:result` is a
  real `langgraph.graph/run*` state."
  [actor]
  [(run-op! actor "commit-1-log-record"
         {:op :log-field-record :field-id "paddy-001"
          :acreage 12.5 :water-level 5 :variety "japonica"
          :record-type "planting"})

   (run-op! actor "commit-2-schedule-drainage"
         {:op :schedule-field-operation :field-id "paddy-002"
          :operation-type "midseason-drainage"
          :requested-date "2026-08-02"
          :reason "midseason aeration per variety schedule"})

   (run-op! actor "escalate-1-crop-health-concern"
         {:op :flag-crop-health-concern :field-id "paddy-002"
          :concern "blast fungus lesions on lower leaves, sector B; drought-stressed edge rows"})

   (run-op! actor "escalate-2-high-cost-supply-order"
         {:op :order-supplies :field-id "paddy-003"
          :category "equipment" :cost 1200})

   (run-op! actor "hold-1-field-not-registered"
         {:op :log-field-record :field-id "paddy-099"
          :acreage 5 :water-level 3})

   (run-op! actor "hold-2-irrigation-equipment-blocked"
         {:op :operate-irrigation-equipment :field-id "paddy-001"
          :note "pump valve override request"})

   (run-op! actor "hold-3-op-not-allowed"
         {:op :inspect-drone-flyover :field-id "paddy-001"})

   (run-op! actor "hold-4-water-level-invalid"
         {:op :log-field-record :field-id "paddy-003"
          :acreage 6 :water-level -1.5})])

(def ^:private human-notes
  "Free-text context a human reviewer supplied alongside their REAL
  approval decision below -- this is NOT part of the actor's own
  output, just the record of what the farmer/agronomist actually said
  when reviewing the escalation. Keyed by run `:label`."
  {"escalate-1-crop-health-concern"
   "agronomist consult confirmed blast fungus; fungicide treatment dispatch approved"})

(defn- resolve-approval!
  "Actually RESUMES the interrupted graph run for `label` via
  `langgraph.graph/run*` with `:resume? true` against the SAME
  `thread-id` the original escalation ran under -- a genuine
  checkpoint resume through `riceops.operation/build`'s
  `interrupt-before #{:request-approval}` gate, not a fabricated
  record. `:by`/`:role` and the resulting `:disposition :commit` come
  straight out of the resumed graph state; only `:note` is
  renderer-authored (see `human-notes`)."
  [actor label by]
  {:label label
   :by by
   :role :farm-operator
   :note (get human-notes label)
   :result (:state (g/run* actor {:approval {:status :approved :by by}}
                          {:thread-id label :resume? true}))})

;; ----------------------------- rendering -----------------------------

(defn- esc [v]
  (-> (str v)
      (str/replace "&" "&amp;")
      (str/replace "<" "&lt;")
      (str/replace ">" "&gt;")))

(defn- disposition-badge [disposition]
  (case disposition
    :commit   "<span class=\"ok\">commit</span>"
    :escalate "<span class=\"warn\">escalate</span>"
    :hold     "<span class=\"err\">HOLD</span>"
    (str "<span class=\"muted\">" (esc disposition) "</span>")))

(defn- basis-text
  "Human-readable basis for a run's disposition. For :escalate, the raw
  `disposition-fact`'s `:reason` is `:always-escalate` for BOTH a
  literal always-escalate op AND a high-stakes high-cost order (see
  `riceops.operation`'s `:decide` node -- `:high-stakes?` collapses
  both into the same reason keyword); we disambiguate using the real,
  independently-checkable governor data
  (`riceops.governor/always-escalate-ops` membership + the request's
  own `:cost`) rather than inventing new wording."
  [{:keys [request result]}]
  (let [{:keys [disposition audit verdict]} result
        disposition-fact (second audit)]
    (case disposition
      :commit (str "committed · basis: " (str/join ", " (:basis disposition-fact)))
      :escalate (cond
                  (contains? governor/always-escalate-ops (:op request))
                  "always-escalate op -- human sign-off required regardless of confidence"

                  (:cost request)
                  (str "high-cost: " (:cost request) " exceeds escalation threshold")

                  :else (str "reason: " (name (or (:reason disposition-fact) :unknown))))
      :hold (str/join "; " (map #(str (name (:rule %)) " — " (:detail %))
                                 (:violations verdict)))
      "")))

(defn- op-row [{:keys [label request result] :as run}]
  (format "        <tr><td>%s</td><td><code>%s</code></td><td>%s</td><td>%s</td><td>%s</td></tr>"
          (esc label) (esc (name (:op request))) (esc (:field-id request))
          (disposition-badge (:disposition result))
          (esc (basis-text run))))

(defn- hold-row [{:keys [label request result]}]
  (let [violations (get-in result [:verdict :violations])]
    (str/join "\n"
              (for [v violations]
                (format "        <tr><td>%s</td><td><code>%s</code></td><td><code>%s</code></td><td>%s</td></tr>"
                        (esc label) (esc (name (:op request))) (esc (name (:rule v))) (esc (:detail v)))))))

(defn- sign-off-row [{:keys [label by role note result]}]
  (format "        <tr><td>%s</td><td>%s</td><td>%s (%s)</td><td>%s</td></tr>"
          (esc label)
          (if (= :commit (:disposition result))
            "<span class=\"ok\">approved</span>" "<span class=\"muted\">pending</span>")
          (esc by) (esc (name role)) (esc note)))

(defn- pending-escalation-row [{:keys [label] :as run}]
  (format "        <tr><td>%s</td><td><span class=\"muted\">pending human review</span></td><td>&mdash;</td><td>%s</td></tr>"
          (esc label) (esc (basis-text run))))

(defn- known-op-row [op]
  (let [always? (contains? governor/always-escalate-ops op)]
    (format "        <tr><td><code>%s</code></td><td>%s</td></tr>"
            (esc (name op))
            (if always?
              "<span class=\"warn\">always human sign-off</span>"
              "<span class=\"ok\">auto-commit when clean &middot; confidence/cost gates still apply</span>"))))

(defn- blocked-op-row [op]
  (format "        <tr><td><code>%s</code></td><td><span class=\"critical\">permanently blocked — %s exclusive authority</span></td></tr>"
          (esc (name op))
          (if (= op :finalize-pesticide-application) "agronomist" "farmer")))

(defn- cost-threshold-row [[_id {:keys [name cost-threshold]}]]
  (format "        <tr><td>%s</td><td>%d</td></tr>" (esc name) cost-threshold))

(defn render
  "Renders the full operator-console.html document from `runs`
  (`run-demo!`'s return value) and `approvals`
  (`resolve-approval!` calls, one per resolved escalation)."
  [runs approvals]
  (let [commit-runs (filter #(= :commit (:disposition (:result %))) runs)
        escalate-runs (filter #(= :escalate (:disposition (:result %))) runs)
        hold-runs (filter #(= :hold (:disposition (:result %))) runs)
        resolved-labels (set (map :label approvals))
        pending-runs (remove #(resolved-labels (:label %)) escalate-runs)
        op-rows (str/join "\n" (map op-row runs))
        hold-rows (str/join "\n" (keep #(let [r (hold-row %)] (when (seq r) r)) hold-runs))
        sign-off-rows (str/join "\n" (map sign-off-row approvals))
        pending-rows (str/join "\n" (map pending-escalation-row pending-runs))
        known-op-rows (str/join "\n" (map known-op-row (sort governor/known-ops)))
        blocked-op-rows (str/join "\n" (map blocked-op-row (sort governor/blocked-ops)))
        threshold-rows (str/join "\n" (map cost-threshold-row (sort-by first facts/supply-categories)))]
    (str
     "<html><head><meta charset=\"utf-8\"><title>cloud-itonami-isic-0112 · rice-paddy operations coordinator</title><style>\n"
     "table { width: 100%; border-collapse: collapse; font-size: 14px; }\n"
     ".ok { color: #137a3f; }\n"
     "body { font-family: system-ui,-apple-system,sans-serif; margin: 0; color: #1a1a1a; background: #fafafa; }\n"
     "header.bar { display: flex; align-items: center; gap: 12px; padding: 12px 20px; background: #fff; border-bottom: 1px solid #e5e5e5; }\n"
     "th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #f0f0f0; }\n"
     "h2 { margin-top: 0; font-size: 15px; }\n"
     ".warn { color: #b25c00; background: #fff8e1; padding: 2px 6px; border-radius: 4px; }\n"
     "main { max-width: 980px; margin: 24px auto; padding: 0 20px; }\n"
     "header.bar h1 { font-size: 18px; margin: 0; font-weight: 600; }\n"
     ".muted { color: #888; font-size: 13px; }\n"
     ".critical { color: #fff; background: #b3261e; padding: 2px 6px; border-radius: 4px; font-weight: 600; }\n"
     ".card { background: #fff; border: 1px solid #e5e5e5; border-radius: 8px; padding: 16px; margin-bottom: 16px; }\n"
     ".err { color: #fff; background: #b3261e; padding: 2px 6px; border-radius: 4px; font-weight: 600; }\n"
     "th { font-weight: 600; color: #555; font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; }\n"
     "header.bar .badge { margin-left: auto; font-size: 12px; color: #666; }\n"
     "code { font-size: 12px; background: #f4f4f4; padding: 1px 4px; border-radius: 3px; }\n"
     "</style></head><body>\n"
     "<header class=\"bar\">\n"
     "  <h1>Rice-Paddy Operations Coordinator (ISIC 0112) — Operator Console</h1>\n"
     "  <span class=\"badge\">read-only sample · governor-gated · never operates field/irrigation equipment</span>\n"
     "</header>\n"
     "<main>\n"
     "  <section class=\"card\">\n"
     "    <h2>Operation log (" (count runs) " requests · "
     (count commit-runs) " commit / " (count escalate-runs) " escalate / " (count hold-runs) " hold)</h2>\n"
     "    <p class=\"muted\">Demo snapshot — build-time-generated from the compiled <code>riceops.operation/build</code> StateGraph via <code>riceops.render-html</code> (<code>clojure -M:dev:render-html</code>), regenerated nightly.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Run</th><th>Op</th><th>Field</th><th>Disposition</th><th>Basis</th></tr></thead>\n"
     "      <tbody>\n"
     op-rows "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"
     "  <section class=\"card\">\n"
     "    <h2>HARD holds (independent Governor rules, never overridable)</h2>\n"
     "    <p class=\"muted\">Each row is a DISTINCT real <code>riceops.governor</code> violation rule, independently tripped in this run — not a hand-typed transcript.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Run</th><th>Op</th><th>Rule</th><th>Detail</th></tr></thead>\n"
     "      <tbody>\n"
     hold-rows "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"
     "  <section class=\"card\">\n"
     "    <h2>Escalations — human sign-off</h2>\n"
     "    <p class=\"muted\">A resolved escalation below is a genuine checkpoint resume (<code>interrupt-before #{:request-approval}</code>, <code>langgraph.graph/run*</code> with <code>:resume? true</code>) through the compiled StateGraph — not a second governor pass and not a fabricated record. Only the reviewer's free-text note is renderer-authored.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Run</th><th>Resolution</th><th>Signed off by</th><th>Note</th></tr></thead>\n"
     "      <tbody>\n"
     sign-off-rows "\n"
     (when (seq pending-rows) (str pending-rows "\n"))
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"
     "  <section class=\"card\">\n"
     "    <h2>Action gate (Paddy Operations Governor)</h2>\n"
     "    <p class=\"muted\">Confidence floor <code>" governor/confidence-floor "</code> · default supply-order cost threshold <code>" facts/default-cost-threshold "</code>. HARD holds cannot be overridden; direct field/irrigation-equipment operation and pesticide-decision finalization are permanently blocked.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Op</th><th>Gate</th></tr></thead>\n"
     "      <tbody>\n"
     known-op-rows "\n"
     blocked-op-rows "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"
     "  <section class=\"card\">\n"
     "    <h2>Supply-order cost thresholds (<code>riceops.facts/supply-categories</code>)</h2>\n"
     "    <table>\n"
     "      <thead><tr><th>Category</th><th>Escalation threshold</th></tr></thead>\n"
     "      <tbody>\n"
     threshold-rows "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"
     "</main>\n"
     "</body></html>\n")))

(defn -main [& args]
  (let [out (or (first args) "docs/samples/operator-console.html")
        actor (op/build (seed-store))
        runs (run-demo! actor)
        approvals [(resolve-approval! actor "escalate-1-crop-health-concern" "op-1")]
        html (render runs approvals)]
    (when-let [parent (.getParentFile (java.io.File. ^String out))]
      (.mkdirs parent))
    (spit out html)
    (println "wrote" out "("
             (count runs) "runs,"
             (count (filter #(= :commit (:disposition (:result %))) runs)) "commit,"
             (count (filter #(= :escalate (:disposition (:result %))) runs)) "escalate,"
             (count (filter #(= :hold (:disposition (:result %))) runs)) "hold ·"
             (count approvals) "escalation(s) resolved via real checkpoint resume )")))
